### ISSUE TITLE
ERROR: default.html.twig template not found for page: /

### ISSUE THREAD

**Issue by timconsidine** [hibbitts-design/grav-theme-bootstrap4-open-matter#10]
Clean grav install and theme installed via Tools -> Direct Install
Only one page
How can I resolve this

**Comment by paulhibbitts** [comment]
Hi @timconsidine , I am not sure why that is happening. Can you do the same process with the parent Bootstrap4 theme?

I have not used direct install, and the theme has dependencies which I am not sure are handled that way. Can you install the theme ok via CLI or Admin? Thanks!

**Comment by paulhibbitts** [comment]
I've been able to confirm that Direct Install does NOT take care of any theme dependencies. So you could either add all of these manually (see https://github.com/hibbitts-design/grav-theme-bootstrap4-open-matter/blob/master/blueprints.yaml#L18-L30) or use CLI or the Admin Panel to install then theme.
