### ISSUE TITLE
Making sure this is the right theme?

### ISSUE THREAD

**Issue by BigDC** [hibbitts-design/grav-theme-bootstrap4-open-matter#11]
Ok so let me just be sure, Does this theme have the capabilities of GLOBAL sidebars. In other words, having the capability to have a sidebarr on any or all pages including the blog?  If so, please take me step by step on how to do it, please?

How can I add a custom logo to the site?

**Comment by paulhibbitts** [comment]
Hi @BigDC , as I mentioned the best way for you to explore the theme capabilities (i.e. working examples) and confirm it can do what you are looking for is to review the skeleton of that theme, in this case that would be the Open Course Hub Site skeleton at https://getgrav.org/downloads/skeletons and online at https://demo.hibbittsdesign.org/grav-open-matter-course-hub/. Give that a look over and hopefully that should show you an example of what you are looking for.

Re: Custom logo, that is not an option in the Bootstrap4 theme, and so in this case it is not supported in my inherited Bootstrap4 Open Matter theme.
