### ISSUE TITLE
Missing tabs in Templates "Blog" and "Item"

### ISSUE THREAD

**Issue by dioridna** [hibbitts-design/grav-theme-bootstrap4-open-matter#14]
For some time now, in new/fresh GRAV installations (basic installation with admin + any Bootstrap4 theme) with activated Bootstrap4 theme, the “Blog List” tab is no longer displayed on the pages with the “Blog” template and the “Blog Item” tab on the pages with the “Item” template.
Is this only the case for me? Thank you for support.

**Comment by dioridna** [comment]
Solution:
https://discourse.getgrav.org/t/missing-tabs-in-bootstrap4-theme/20835/3

**Comment by paulhibbitts** [comment]
Thanks for the heads-up, looks like my inherited theme has the needed updated YAML already.
