### ISSUE TITLE
Disable Git requirement.

### ISSUE THREAD

**Issue by timgray** [hibbitts-design/grav-theme-bootstrap4-open-matter#4]
I do not want the Git links all over my pages and I dont want to use Git with this.  how do I disable the requirement for Git and or get rid of the links in the menu telling all of my sites visitors to "configure git"

**Comment by paulhibbitts** [comment]
Hello @timgray , to hide the Git Sync Link from all pages go to the settings for the Active Theme and choose "None" for "Location of Git Sync Link"

![2019-08-11_08-45-05](https://user-images.githubusercontent.com/1812771/62836074-746a4480-bc14-11e9-9332-4ec797fca0d4.png)

As Git Sync support is one of the main features of the theme it is enabled by default. If you would like to use a very similar theme without Git Sync at all take a look at Bootstrap4 (https://github.com/trilbymedia/grav-theme-bootstrap4), which is the parent theme of Bootstrap4 Open Matter.

**Comment by paulhibbitts** [comment]
I am going to close this issue now, if the answer does not answer your question please let me know.
