### ISSUE TITLE
Fatal Error Installing Theme Dependencies

### ISSUE THREAD

**Issue by kevinamezaga** [hibbitts-design/grav-theme-bootstrap4-open-matter#5]
Installing this theme and its dependencies creates an error with Grav that requires an uninstall of all dependencies.

![image](https://user-images.githubusercontent.com/25387497/66432411-f8119900-e9eb-11e9-8382-6f7ef144b8c0.png)

**Comment by paulhibbitts** [comment]
Hi @kevinamezaga , it looks like your server does have grant permissions for Exec (PHP) to run, which the Git Sync requires, which then causes this unfortunate error. If you would like to use this theme which sets Git Sync as a dependency you could contact your host provider and get Exec permission to run. If not, unfortunately, this theme will not work.

Please let me know if any additional information is helpful etc. I wish I could catch this error in a nicer way but currently this is not possible.

**Comment by paulhibbitts** [comment]
I am going to close this issue now, but if I can be of more help please let me know.
