### ISSUE TITLE
Theme stylesheet option not working

### ISSUE THREAD

**Issue by Nithilher** [hibbitts-design/grav-theme-bootstrap4-open-matter#8]
I installed the theme and moved the blog pages from the _demo folder to the pages folder to test it. I configured the theme within the admin panel of grav. However, when selecting a theme stylesheet, not all theming is done. For example, selecting "cosmo" or "darkly" leads to lots of text in white color on white background, such that I cannot read large parts of the content. I did expect the background color to change as well, but seems to stay white whatever theme stylesheet I chose. 

Running bootstrap4-open-matter 3.2.3, Grav v1.6.26, Admin v1.9.15. I attached two screenshots from the article "typography" from within the demo blog provided by the theme, when "darkly" was selected as theme style.

<img width="1072" alt="darkly" src="https://user-images.githubusercontent.com/12639351/84829624-56d1ec80-b028-11ea-9ba3-d9974a3cc4f2.png">
<img width="1063" alt="darkly-text-selected" src="https://user-images.githubusercontent.com/12639351/84829636-5df8fa80-b028-11ea-9f9d-6fc4860499c8.png">

**Comment by paulhibbitts** [comment]
Hi @Nithilher, this might be an issue related to using those options via a theme install with a default theme YAML file vs. a fully pre-configured skeleton. Could you please test the same options with the Skeleton? https://github.com/hibbitts-design/grav-skeleton-course-hub/releases/download/v3.1.8/grav-skeleton-open-matter-course-hub-site.zip

**Comment by Nithilher** [comment]
Installed the skeleton. Clean install, nothing else. 
The problem ist the same. The background in most elements stays white, colours of text is partially changed to light colours so text becomes unreadable, after changing to "darkly" within theme configuration (admin-panel -> themes -> clicking on the theme -> theme style)
<img width="1038" alt="open-matter-darkly" src="https://user-images.githubusercontent.com/12639351/84899624-3138f780-b0a9-11ea-9ea5-a4d17d224d07.png">
<img width="1027" alt="open-matter-skeleton-textselect" src="https://user-images.githubusercontent.com/12639351/84899637-34cc7e80-b0a9-11ea-8802-79a10dc170c7.png">

**Comment by paulhibbitts** [comment]
Thanks for testing that @Nithilher, I will look into this more and report back any findings.

**Comment by paulhibbitts** [comment]
Hi @Nithilher , I think that for that theme the appearance is correct. It looks like it assumes a dark page color, which the Bootstrap4 Open Matter theme does not support (but you could do via Custom CSS): https://bootswatch.com/darkly/

Do the other theme styles work?

**Comment by Nithilher** [comment]
Only the theme styles which assume a light background work. So "Cyborg", "Slate", "Superhero" or "Solar" do not work properly, either. 

I had hoped that I could get a dark theme without too much customising myself. 

Btw, it is not sufficient to set these background colours in custom.css. They are still overridden by what is in theme.css. As far as I can see, theme.css defines a background colour for "main-content". That name does never appear in the css files of the different theme styles in the bootswatch directory. That is why their background colour settings have almost no effect. My impression is that main-content is an additional layer between body and almost everything else, except header and footer. If I comment out the background colour definition in the "main-content" definitions in theme.css, the theme styles work (mostly), and settings of background colours for, e.g. "body" in custom.css have an effect.

**Comment by paulhibbitts** [comment]
Sorry @Nithilher but the support for Bootswatch theme styles is pretty limited in my theme so you might not be able to do what you are looking for. My CSS skills are only basic at best🙂

**Comment by Nithilher** [comment]
No problem. 
I once made my own theme from scratch, but that was in times, where nobody thought of mobile devices and full responsive themes. Now I need a new theme which looks good on mobile devices as well. I'll see what I have to customise in custom.css to get it running. Many thanks for your help!
