### ISSUE TITLE
incorrect quote characters in presentation.yaml

### ISSUE THREAD

**Issue by SteveDaulton** [hibbitts-design/grav-theme-bootstrap4-open-matter#9]
Line 257 of grav-admin/user/themes/bootstrap4-open-matter/blueprints/presentation.yaml
description: ''Short name, e.g. ''file''.'
Should be:
description: 'Short name, e.g. "file".'
Note the use of two ' 'single quotes' ' that should each be one "double quote"

**Comment by paulhibbitts** [comment]
Thanks for making this issue here @SteveDaulton , I will take a look at this.

**Comment by paulhibbitts** [comment]
Fixed in the most recent release, thanks again @SteveDaulton .
